name: Docker Build

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t logger .
      
      - name: Test container
        run: |
          mkdir -p logs
          echo -e "test1\ntest2\ntest3" | docker run -i -v $(pwd)/logs:/home/logs/ logger
          cat logs/log.txt
