name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          cmake -H. -B build
          cmake --build build
          cd build
          cmake -G "TGZ" . && cmake --build . --target package
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
